resolver: ghc-8.6.3
packages:
- .
extra-deps: 
    - scotty-0.11.5
    - aeson-1.4.7.1
    - blaze-builder-0.4.1.0
    - case-insensitive-1.2.1.0
    - data-default-class-0.1.2.0
    - exceptions-0.10.4
    - fail-4.9.0.0
    - http-types-0.12.3
    - monad-control-1.0.2.3
    - nats-1.1.2
    - network-3.1.1.1
    - regex-compat-0.95.2.0
    - transformers-base-0.4.5.2
    - transformers-compat-0.6.5
    - wai-3.2.2.1
    - wai-extra-3.0.29.1
    - warp-3.3.10
    - ansi-terminal-0.10.3
    - async-2.2.2
    - attoparsec-0.13.2.4
    - auto-update-0.1.6
    - base-compat-batteries-0.11.1
    - base-orphans-0.8.2
    - base64-bytestring-1.0.0.3
    - bsb-http-chunked-0.0.0.4
    - cookie-0.4.5
    - dlist-0.8.0.8
    - fast-logger-3.0.1
    - hashable-1.3.0.0
    - http-date-0.0.8
    - http2-2.0.4
    - iproute-1.7.9
    - old-locale-1.0.0.7
    - primitive-0.7.0.1
    - regex-base-0.94.0.0
    - regex-posix-0.96.0.0
    - resourcet-1.2.3
    - scientific-0.3.6.2
    - simple-sendfile-0.2.30
    - streaming-commons-0.2.1.2
    - tagged-0.8.6
    - th-abstraction-0.3.2.0
    - time-compat-1.9.3
    - time-manager-0.0.0
    - unix-compat-0.5.2
    - unordered-containers-0.2.10.0
    - uuid-types-1.0.3
    - vault-0.3.1.4
    - vector-0.12.1.2
    - void-0.7.3
    - wai-logger-2.3.6
    - word8-0.1.3
    - x509-1.7.5
    - zlib-0.6.2.1
    - appar-0.1.8
    - asn1-encoding-0.9.6
    - asn1-parse-0.9.5
    - asn1-types-0.3.4
    - base-compat-0.11.1
    - byteorder-1.0.4
    - cabal-doctest-1.0.8
    - colour-2.3.5
    - cryptonite-0.26
    - easy-file-0.2.2
    - hourglass-0.2.12
    - integer-logarithms-1.0.3
    - memory-0.15.0
    - network-byte-order-0.1.4.0
    - pem-0.2.4
    - psqueues-0.2.7.2
    - random-1.1
    - semigroups-0.19.1
    - unix-time-0.4.7
    - unliftio-core-0.2.0.1
    - basement-0.0.11
    - old-time-1.1.0.3
    - postgresql-simple-0.6.2
    - Only-0.1
    - bytestring-builder-0.10.8.2.0
    - postgresql-libpq-0.9.4.2
    - resource-pool-0.2.3.2
    - MissingH-1.4.3.0
    - wai-middleware-static-0.8.3
    - configurator-0.3.0.0
    - expiring-cache-map-0.0.6.1
    - hslogger-1.3.1.0
    - mime-types-0.1.0.9
    - network-bsd-2.8.1.0
    - network-uri-2.6.3.0
    - lens-aeson-1.0.2
    - comonad-5.0.6
    - lens-4.19.2
    - bifunctors-5.5.7
    - call-stack-0.2.0
    - free-5.1.3
    - adjunctions-4.4
    - invariant-0.5.3
    - kan-extensions-5.2
    - contravariant-1.5.2
    - distributive-0.6.2
    - parallel-3.2.2.0
    - profunctors-5.5.2
    - reflection-2.1.4
    - semigroupoids-5.3.4 
    - split-0.2.3.4
    - StateVar-1.2
    - prelude-extras-0.4.0.3
    - wreq-0.5.3.2
    - authenticate-oauth-1.6.0.1
    - base16-bytestring-0.1.1.6
    - http-client-0.6.4.1
    - http-client-tls-0.3.5.3
    - time-locale-compat-0.1.1.5
    - RSA-2.4.1
    - SHA-1.6.4.4
    - connection-0.3.1
    - crypto-pubkey-types-0.4.3
    - data-default-0.7.1.1
    - tls-1.5.4
    - cereal-0.5.8.1
    - crypto-api-0.13.3
    - data-default-instances-containers-0.0.1
    - data-default-instances-dlist-0.0.1
    - data-default-instances-old-locale-0.0.1
    - socks-0.6.1
    - x509-store-1.6.7
    - x509-system-1.6.6
    - x509-validation-1.6.11
    - entropy-0.4.1.6
